name: expandable_bottom_bar
description: Expandable bottom app bar widget for Flutter SDK
author: ratIIh <ratealt@gmail.com>
homepage: https://github.com/rIIh/expandable-bottom-bar

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
